# Generated by Django 2.0.7 on 2018-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180720_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
