# Generated by Django 2.0.7 on 2018-07-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='melon_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
