# Generated by Django 2.0.7 on 2018-07-22 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('List_name', models.CharField(default='', max_length=100)),
                ('List_serial', models.AutoField(primary_key=True, serialize=False)),
                ('List_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('Music_name', models.CharField(default='', max_length=100)),
                ('Singer_name', models.CharField(default='', max_length=100)),
                ('Melon_serial', models.IntegerField(default=0)),
                ('Naver_serial', models.IntegerField(default=0)),
                ('Bugs_serial', models.IntegerField(default=0)),
                ('Genie_serial', models.IntegerField(default=0)),
                ('Serial_nubmer', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='Song_list',
            field=models.ManyToManyField(to='musics.Music'),
        ),
    ]
