# Generated by Django 2.0.7 on 2018-07-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Melon_serial', models.IntegerField(default=0)),
                ('Naver_serial', models.IntegerField(default=0)),
                ('Bugs_serial', models.IntegerField(default=0)),
                ('Genie_serial', models.IntegerField(default=0)),
                ('Music_Name', models.CharField(max_length=100)),
                ('Singer_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('Serial_nubmer', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='Rookie_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.Music'),
        ),
    ]
