# Generated by Django 2.0.7 on 2018-07-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Music_Name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Singer_Name',
        ),
        migrations.AddField(
            model_name='music',
            name='Music_Name',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='Singer_Name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
