# Generated by Django 2.0.7 on 2018-07-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
