# Generated by Django 2.0.7 on 2018-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20180717_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Music_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='Singer_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
