# Generated by Django 2.0.7 on 2018-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20180717_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
