# Generated by Django 2.0.7 on 2018-07-22 12:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('musics', '0003_remove_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
