# Generated by Django 2.0.7 on 2018-07-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_music_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='grade',
            new_name='Grade',
        ),
    ]
