# Generated by Django 2.0.7 on 2018-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20180717_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Music_Name',
            new_name='Music_name',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Singer_Name',
            new_name='Singer_name',
        ),
    ]
