# Generated by Django 2.0.7 on 2018-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20180717_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Rookie_serial',
        ),
        migrations.AddField(
            model_name='music',
            name='Bugs_serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='Genie_serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='Melon_serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='Naver_serial',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
