# Generated by Django 2.0.7 on 2018-07-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_auto_20180717_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('List_name', models.CharField(default='', max_length=100)),
                ('List_serial', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='Grade',
        ),
        migrations.AddField(
            model_name='list',
            name='Song_list',
            field=models.ManyToManyField(to='musics.Music'),
        ),
    ]
